Description of getContourPropertiesStats
Home > MLVcode > getContourPropertiesStats.m
getContourPropertiesStats
PURPOSE
[vecLD,histograms,bins,statsNames] = getContourPropertiesStats(vecLD, whichStats, minmaxLen, minmaxCurv, junctionTypes)
SYNOPSIS
function [vecLD,histograms,bins,statsNames] = getContourPropertiesStats(vecLD, whichStats, minmaxLen, minmaxCurv, junctionTypes)
DESCRIPTION
 [vecLD,histograms,bins,statsNames] = getContourPropertiesStats(vecLD, whichStats, minmaxLen, minmaxCurv, junctionTypes)
       computes histograms for the contour properties for the vectorized line drawing LD.
 Input:
   vecLD - vectorized line drawing data structure
   whichStats - string or cell array of strings that defines which
                properties to compute. Options are:
                'orientation','length','curvature','junctions'
                default: {'orientation','length','curvature','junctions'}
   minmaxLen - this minimum and maximum for the length histogram
               default: [2, width+length of the image]
   minmaxCurv- this minimum and maximum for the curvature histogram
               default: [0, 90]
   junctionTypes - a cell array with the junction types to incldue in the histogram
                   deault: {} - use all junction types present in this
                   image
 Output:
   vecLD -      vector line drawing with the individual contour stats added
   histograms - cell array of histograms for the features
                in the same order as in whichstats
   bins -       cell array of bin centers for those histograms
                in the same order as in whichstats
   statsNames - the order of stats in the histograms and bins
CROSS-REFERENCE INFORMATION
This function calls:
getCurvatureStats [vecLD,curvatureHistogram,bins] = getCurvatureStats(vecLD,numBins,minmaxCurvature)
getHorizontalVerticalStats [vecLD,HorVerHistogram,bins] = getOrientationStats(vecLD,numBins)
getJunctionStats vecLD = getJunctionStats(vecLD,numAngleBins,junctionTypes)
getLengthStats [vecLD,lengthHistogram,bins] = getLengthStats(vecLD,numBins,minmaxLength)
getOrientationStats [vecLD,oriHistogram,bins] = getOrientationStats(vecLD,numBins)
This function is called by:
saveSceneLDsToTable [resultsTable,statsLD] = saveSceneLDsToTable(csvFileName)
SOURCE CODE
function [vecLD,histograms,bins,statsNames] = getContourPropertiesStats(vecLD, whichStats, minmaxLen, minmaxCurv, junctionTypes)
% [vecLD,histograms,bins,statsNames] = getContourPropertiesStats(vecLD, whichStats, minmaxLen, minmaxCurv, junctionTypes)
%       computes histograms for the contour properties for the vectorized line drawing LD.
% Input:
%   vecLD - vectorized line drawing data structure
%   whichStats - string or cell array of strings that defines which
%                properties to compute. Options are:
%                'orientation','length','curvature','junctions'
%                default: {'orientation','length','curvature','junctions'}
%   minmaxLen - this minimum and maximum for the length histogram
%               default: [2, width+length of the image]
%   minmaxCurv- this minimum and maximum for the curvature histogram
%               default: [0, 90]
%   junctionTypes - a cell array with the junction types to incldue in the histogram
%                   deault: {} - use all junction types present in this
%                   image
%
% Output:
%   vecLD -      vector line drawing with the individual contour stats added
%   histograms - cell array of histograms for the features
%                in the same order as in whichstats
%   bins -       cell array of bin centers for those histograms
%                in the same order as in whichstats
%   statsNames - the order of stats in the histograms and bins
% -----------------------------------------------------
% This file is part of the Mid Level Vision Toolbox:
% http://www.mlvtoolbox.org
%
% Copyright Dirk Bernhardt-Walther
% University of Toronto, Toronto, Ontario, Canada, 2022
%
% Contact: dirk.walther@gmail.com
%------------------------------------------------------
if nargin < 5
    junctionTypes = {};
end
if nargin < 4
    minmaxCurv = [];
end
if nargin < 3
    minmaxLen = [];
end
if nargin < 2
    whichStats = {'orientation','length','curvature','junctions'};
end
if ~iscell(whichStats)
    whichStats = {whichStats};
end
numBins = 8;
histograms = {};
bins = {};
statsNames = {};
for s = 1:length(whichStats)
    thisStat = lower(whichStats{s});
    switch thisStat
        case 'orientation'
            [vecLD,histograms{end+1},bins{end+1},statsNames{end+1}] = getOrientationStats(vecLD,numBins);
        case 'horver'
            [vecLD,histograms{end+1},bins{end+1},statsNames{end+1}] = getHorizontalVerticalStats(vecLD,numBins);
        case 'length'
            if isempty(minmaxLen)
                [vecLD,histograms{end+1},bins{end+1},statsNames{end+1}] = getLengthStats(vecLD,numBins);
            else
                [vecLD,histograms{end+1},bins{end+1},statsNames{end+1}] = getLengthStats(vecLD,numBins,minmaxLen);
            end
        case 'curvature'
            if isempty(minmaxCurv)
                [vecLD,histograms{end+1},bins{end+1},statsNames{end+1}] = getCurvatureStats(vecLD,numBins);
            else
                [vecLD,histograms{end+1},bins{end+1},statsNames{end+1}] = getCurvatureStats(vecLD,numBins,minmaxCurv);
            end
        case 'junctions'
            if isempty(junctionTypes)
                [vecLD,jHist,jBins,jNames] = getJunctionStats(vecLD,numBins);
            else
                [vecLD,jHist,jBins,jNames] = getJunctionStats(vecLD,numBins,junctionTypes);
            end
            histograms = [histograms,jHist];
            bins = [bins,jBins];
            statsNames = [statsNames,jNames];
        otherwise
            error(['Unknown property: ',thisStat]);
    end
end