Description of acfDemoInria
Home > MLVcode > edges-master > toolbox-master > detector > acfDemoInria.m
acfDemoInria
PURPOSE
Demo for aggregate channel features object detector on Inria dataset.
SYNOPSIS
This is a script file.
DESCRIPTION
 Demo for aggregate channel features object detector on Inria dataset.
 See also acfReadme.m
 Piotr's Computer Vision Matlab Toolbox      Version 3.40
 Copyright 2014 Piotr Dollar.  [pdollar-at-gmail.com]
 Licensed under the Simplified BSD License [see external/bsd.txt]
CROSS-REFERENCE INFORMATION
This function calls:
acfDetect Run aggregate channel features object detector on given image(s).
acfModify Modify aggregate channel features object detector.
acfTest Test aggregate channel features object detector given ground truth.
acfTrain Train aggregate channel features object detector.
bbApply Functions for manipulating bounding boxes (bb).
bbGt Bounding box (bb) annotations struct, evaluation and sampling routines.
This function is called by:
SOURCE CODE
% Demo for aggregate channel features object detector on Inria dataset.
%
% See also acfReadme.m
%
% Piotr's Computer Vision Matlab Toolbox      Version 3.40
% Copyright 2014 Piotr Dollar.  [pdollar-at-gmail.com]
% Licensed under the Simplified BSD License [see external/bsd.txt]
%% extract training and testing images and ground truth
cd(fileparts(which('acfDemoInria.m'))); dataDir='../../data/Inria/';
for s=1:2, pth=dbInfo('InriaTest');
  if(s==1), set='00'; type='train'; else set='01'; type='test'; end
  if(exist([dataDir type '/posGt'],'dir')), continue; end
  seqIo([pth '/videos/set' set '/V000'],'toImgs',[dataDir type '/pos']);
  seqIo([pth '/videos/set' set '/V001'],'toImgs',[dataDir type '/neg']);
  V=vbb('vbbLoad',[pth '/annotations/set' set '/V000']);
  vbb('vbbToFiles',V,[dataDir type '/posGt']);
end
%% set up opts for training detector (see acfTrain)
opts=acfTrain(); opts.modelDs=[100 41]; opts.modelDsPad=[128 64];
opts.posGtDir=[dataDir 'train/posGt']; opts.nWeak=[32 128 512 2048];
opts.posImgDir=[dataDir 'train/pos']; opts.pJitter=struct('flip',1);
opts.negImgDir=[dataDir 'train/neg']; opts.pBoost.pTree.fracFtrs=1/16;
opts.pLoad={'squarify',{3,.41}}; opts.name='models/AcfInria';
%% optionally switch to LDCF version of detector (see acfTrain)
if(0)
  opts.filters=[5 4]; opts.pJitter=struct('flip',1,'nTrn',3,'mTrn',1);
  opts.pBoost.pTree.maxDepth=3; opts.pBoost.discrete=0; opts.seed=2;
  opts.pPyramid.pChns.shrink=2; opts.name='models/LdcfInria';
end
%% train detector (see acfTrain)
detector = acfTrain(opts);
%% modify detector (see acfModify)
pModify=struct('cascThr',-1,'cascCal',.01);
detector=acfModify(detector,pModify);
%% run detector on a sample image (see acfDetect)
imgNms=bbGt('getFiles',{[dataDir 'test/pos']});
I=imread(imgNms{1}); tic, bbs=acfDetect(I,detector); toc
figure(1); im(I); bbApply('draw',bbs); pause(.1);
%% test detector and plot roc (see acfTest)
[miss,~,gt,dt]=acfTest('name',opts.name,'imgDir',[dataDir 'test/pos'],...
  'gtDir',[dataDir 'test/posGt'],'pLoad',opts.pLoad,...
  'pModify',pModify,'reapply',0,'show',2);
%% optional timing test for detector (should be ~30 fps)
if(0)
  detector1=acfModify(detector,'pad',[0 0]); n=60; Is=cell(1,n);
  for i=1:n, Is{i}=imResample(imread(imgNms{i}),[480 640]); end
  tic, for i=1:n, acfDetect(Is{i},detector1); end;
  fprintf('Detector runs at %.2f fps on 640x480 images.\n',n/toc);
end
%% optionally show top false positives ('type' can be 'fp','fn','tp','dt')
if(0), bbGt('cropRes',gt,dt,imgNms,'type','fp','n',50,...
    'show',3,'dims',opts.modelDs([2 1])); end